name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
template: |
  # What's Changed

  $CHANGES
categories:
  - title: 'Features'
    label:
      - 'Feature Request'
      - 'Extend Component'
      - 'New Component'
  - title: 'Bugfixes'
    label:
      - 'Bug'
      - 'UI Mismatch'
  - title: 'Refactoring'
    label: 'Functional Component Conversion'
