import { Story, Meta } from '@storybook/react';
import { Props } from './Select';
declare const _default: Meta<import("@storybook/react").Args>;
export default _default;
export declare const Interactive: any;
export declare const RealisticExample: Story<Props>;
export declare const Groups: any;
export declare const TransformFunctionForCustomFilter: any;
export declare const TransformFunctionForNoFilter: any;
export declare const CustomComponents: any;
export declare const RemoveToggleButton: any;
export declare const LoadingState: any;
export declare const InitiallyOpen: any;
export declare const HelperText: any;
export declare const Placeholder: any;
export declare const Label: any;
export declare const DownshiftOptions: any;
export declare const Disabled: any;
export declare const DisableTyping: any;
export declare const DisabledOptions: any;
export declare const ControlledSelectedItem: Story<Props>;
export declare const ControlledIsOpen: Story<Props>;
export declare const ControlledInputValue: Story<Props>;
export declare const Invalid: any;
export declare const DisableAutocomplete: any;
export declare const FocusCallbacks: Story<Props>;
export declare const OnClearCallback: Story<Props>;
export declare const ConfigurableWidth: any;
export declare const Small: any;
export declare const EmptyListText: any;
export declare const AsyncItems: Story<Props>;
