import { Meta } from '@storybook/react';
declare const _default: Meta<import("@storybook/react").Args>;
export default _default;
export declare const Default: any;
export declare const HoverToOpen: any;
export declare const DropdownWithIconAndDefaultIconColour: any;
export declare const DropdownWithHoverLineEffect: any;
export declare const DropdownWithRightPlacement: any;
export declare const DropdownWithFullWidth: any;
export declare const DisabledDropdown: any;
